### ISSUE TITLE
multiextractor requires consumers to modify their nuget.config

### ISSUE THREAD

**Issue by gfs** [microsoft/OSSGadget#109]
This should not be required perhaps we can include the dlls directly in the multi extractor nupkg.

**Comment by gfs** [comment]
Maybe this can be fixed by including a nuget.config in the nupkg itself?

**Comment by gfs** [comment]
@daalcant

**Comment by daalcant** [comment]
Resolved (ish) after reverting to older version of DiscUtils. WIP to see if we can get the updated version on NuGet.
