### ISSUE TITLE
oss-detect-backdoor fails with error message on all packages

### ISSUE THREAD

**Issue by jacobmsft** [microsoft/OSSGadget#111]
Linux:
> ./oss-detect-backdoor pkg:npm/express
Error analyzing /tmp/dgzxagdo.gob/npm-express@5.0.0-alpha.8: Invalid rule path Resources\BackdoorRules

Windows:
>.\oss-detect-backdoor.exe pkg:npm/express
[35mError analyzing C:\Users\sujacob\AppData\Local\Temp\5njmzwnf.abr\npm-express@5.0.0-alpha.8: Duplicate ruleId BD000200 found.[0m

**Comment by scovetta** [comment]
Fixed in #131
