### ISSUE TITLE
Add SDL/1CS Task to Pipeline

### ISSUE THREAD

**Issue by guyacosta** [microsoft/OSSGadget#119]
Need the following tasks to be added to the core or a new sdl pipeline:
credscanner
codeinspector 

i.e.
- task: CredScan@3
  inputs:
    outputFormat: 'sarif'

- task: CodeInspector@2
  inputs:
    ProductId: 'e6121b8f-ffd8-40b1-981d-a5ea5c121baa'

**Comment by daalcant** [comment]
Done
