### ISSUE TITLE
Unable to update DevSkim to OAT-enabled version

### ISSUE THREAD

**Issue by scovetta** [microsoft/OSSGadget#148]
When we update the DevSkim dependency to the latest version, we get a few errors:

https://github.com/microsoft/OSSGadget/blob/main/src/oss-detect-cryptography/DetectCryptographyTool.cs#L408

`rules.Count()` fails because `_rules` is not populated, only `_oatRules`. I think `Count()` should reflect `_oatRules` instead.

https://github.com/microsoft/OSSGadget/blob/main/src/oss-detect-cryptography/DetectCryptographyTool.cs#L478

The call into Analyze actually completes, but doesn't give the expected results. I was having a hard time tracing to see where we were getting different results.
Repro:
Using DevSkim v0.4.144
```
PS C:\Users\scovetta\source\repos\OSSGadget\src\oss-detect-cryptography\bin\Debug\netcoreapp3.1> .\oss-detect-cryptography.exe pkg:npm/md5.js
Microsoft OSS Gadget - oss-detect-cryptography 0.1.0.0
[X] pkg:npm/md5.js - This software package appears to implement Hash.MD5.
[ ] pkg:npm/md5.js - This software package does NOT have a high-density of cryptographic operators.
[ ] pkg:npm/md5.js - This software package does NOT contains words that suggest cryptography.
```

Using DevSkim v0.4.188
```
PS C:\Users\scovetta\source\repos\OSSGadget\src\oss-detect-cryptography\bin\Debug\netcoreapp3.1> .\oss-detect-cryptography.exe pkg:npm/md5.js
Microsoft OSS Gadget - oss-detect-cryptography 0.1.0.0
[ ] pkg:npm/md5.js - This software package does NOT appear to implement cryptography.
```

**Comment by gfs** [comment]
I'm looking at the source code for the latest and the count method appears to use OAT Rule. https://github.com/microsoft/DevSkim/blob/main/DevSkim-DotNet/Microsoft.DevSkim/Ruleset.cs. This should be fixed just by updating to the latest devskim.

**Comment by gfs** [comment]
Using Devskim v0.4.200
> gabe@DOOM oss-detect-cryptography % dotnet bin/Debug/net5.0/oss-detect-cryptography.dll pkg:npm/md5.js
Microsoft OSS Gadget - oss-detect-cryptography 0.1.0.0
[X] pkg:npm/md5.js - This software package appears to implement Hash.MD5.
[ ] pkg:npm/md5.js - This software package does NOT have a high-density of cryptographic operators.
[ ] pkg:npm/md5.js - This software package does NOT contains words that suggest cryptography.

**Comment by gfs** [comment]
This will be fixed with the merge of #175 just bumping the dependencies.

**Comment by gfs** [comment]
PR For Dependencies is still open.  We are seeing some test failures to investigate. #176

**Comment by gfs** [comment]
There seems to be an issue perhaps with case insensitivity.  This still appears to be working in DevSkim/OAT directly as I wrote a new test case for it.
