### ISSUE TITLE
Type initializer error for libgit2sharp on Linux

### ISSUE THREAD

**Issue by scovetta** [microsoft/OSSGadget#172]
Here is the error:
```
root@3d51e1d89ad7:/opt/src/work# oss-download -e pkg:github/neuecc/MessagePack-CSharp@v2.2.60
Error downloading GitHub package: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
```

Using 0.1.249 [link](https://github.com/microsoft/OSSGadget/releases/download/v0.1.249/OSSGadget_linux_0.1.249.zip) on Ubuntu 20.04.

This seems to be related to https://github.com/libgit2/libgit2sharp/issues/1703.

**Comment by gfs** [comment]
It looks like libgit2sharp isn't supported on 20.04 and there doesn't appear to be urgency to release support.  There are some possible workarounds mentioned in the linked bug and others that I can investigate.

**Comment by scovetta** [comment]
Looks like there is a [fixed version](https://www.nuget.org/packages/LibGit2Sharp/0.27.0-preview-0096) of libgit2sharp out now, but when I tried, I'm now getting:

```
Error downloading GitHub package: failed to mmap. Could not write data: Permission denied failed to mmap. Could not write data: Permission denied|
```

**Comment by daalcant** [comment]
Removed libgit2sharp dep with #228
