### ISSUE TITLE
Recent OSS Gadget doesn't work on Linux

### ISSUE THREAD

**Issue by scovetta** [microsoft/OSSGadget#213]
The latest OSS Gadget Linux builds are erroring out, saying that the framework isn't installed. (It shouldn't need to be-- these should be self-contained builds.)

![image](https://user-images.githubusercontent.com/732166/112201866-f16de600-8bcd-11eb-8132-27201f20f20c.png)

**Comment by daalcant** [comment]
Tested latest release against updated Ubuntu 20.04 with the same issue. Looking into this.

**Comment by gfs** [comment]
As before, I strongly recommend not building by the solution and instead building each project.

**Comment by daalcant** [comment]
Yes, this is a side-effect of building from the solution file. When I build from csproj, I am able to produce self-contained applications that function correctly, and can leverage the Single File property as well. 

We ran into this before but settled on building from solution because publishing each tool individually as a self-contained app creates a separate .NET runtime for every output, which drives the release size up by something like 10x. We can still move to publishing via csproj, but this is the tradeoff we have to make if we still want to bundle and release all of the tools together.

**Comment by gfs** [comment]
> We ran into this before but settled on building from solution because publishing each tool individually as a self-contained app creates a separate .NET runtime for every output, which drives the release size up by something like 10x.

Why did that stop working?

> this is the tradeoff we have to make if we still want to bundle and release all of the tools together.

Do we have to distribute platform specific binaries? Once we complete #196 that should be the way to get oss gadget tools.

**Comment by daalcant** [comment]
> Why did that stop working?

At this point I question that it ever worked across all platforms. Maybe I'm confusing this with test work for a different project.

> Do we have to distribute platform specific binaries? Once we complete #196 that should be the way to get oss gadget tools.

No preference here. I agree that Dotnet Global Tools are the easier solution.

**Comment by daalcant** [comment]
I grabbed the very first Linux release of OSSGadget, which from the look of the file structure was also built from the solution file. I still have to chmod +x the executables (I have a fix for that later), but they work fine there. Something definitely changed at some point.

**Comment by scovetta** [comment]
I think it's fine to publish as a global tool *as well* as platform-specific, self-contained packages -- I don't think we should require .NET to be installed in order to use OSS Gadget -- being able to download, extract, and run keeps a low barrier to entry.

I believe 0.1.263 worked as expected, so it might be between then and now.

**Comment by daalcant** [comment]
I'll look into this more tomorrow. When I attempt to run `dotnet publish OSSGadget.sln --self-contained true -r linux-x64` I get some errors complaining about the lack of RuntimeIdentifiers, so maybe adding those to the project files is necessary after all. The `dotnet publish` documentation suggests this shouldn't be necessary, but then again I have also found some issues in the dotnet repo that suggest building from solution is dangerous and ill advised, so we might not have a choice.

**Comment by gfs** [comment]
Why is the library being built at all for the platform specific binaries?

**Comment by gfs** [comment]
Can you configure it to build everything *but* shared so its only building executables and use the self-contained single file publish?

**Comment by daalcant** [comment]
> Can you configure it to build everything _but_ shared so its only building executables and use the self-contained single file publish?

I don't see any reason why we couldn't. For now I'll be focusing on getting the app bundle with a single runtime working again. After that I'll work on #217.

**Comment by daalcant** [comment]
I managed to build from solution and produce functioning self-contained Linux apps. I tested combinations of:
- Using RID csproj properties / not
- Using RID build flags / not
- Using Self-contained build flags (true, false, omitted) / not

Successful combinations below.

In these first two configurations, RID properties must be added to each csproj file. **RID build flags are also required in both cases**, but the self-contained flag appears to be optional. These builds will complete in one step.
1. `dotnet publish .\OSSGadget.sln -c Release -o ExampleOne -r linux-x64 --self-contained true`
2. `dotnet publish .\OSSGadget.sln -c Release -o ExampleTwo -r linux-x64`

In this last configuration, RID properties are **not** added to the csproj files. This method requires two build steps. RID build flags are required in both steps, and self-contained build flags are only required for the 2nd step. I am honestly not sure why this two-step method works, but I stumbled upon it after observing that building from solution has an unusual build order/output order.
Step 1. `dotnet publish .\OSSGadget.sln -c Release -o ExampleThree -r linux-x64`
Step 2. `dotnet publish .\OSSGadget.sln -c Release -o ExampleThree -r linux-x64 --self-contained true --no-build`

Adding RID properties to the csproj files seems much cleaner, but I need to check if doing so causes any unwanted side effects, as we had issues with this in the past but I can't remember why.

**Comment by gfs** [comment]
Thanks for testing. Looks like rids is the way.

**Comment by gfs** [comment]
This is the recommended csproj for publishing single file.  Trimmed is more dangerous, I've seen it break things. Ready to run improves startup time at (I believe) the cost of build time.

It doesn't look like you'd need to specify anything else except the runtime identifier if you added these to the csproj.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

</Project>
```
