### ISSUE TITLE
Wiki link broken

### ISSUE THREAD

**Issue by keeganwitt** [microsoft/OSSGadget#233]
Project has wiki tab enabled, but seems to redirect back to the repo. Not sure if this was intentional or not. From other documentation (like SUPPORT.md) it looks like it's not.

**Comment by gfs** [comment]
I populated the wiki with the information from the readme so it'll be a little easier to find what you're looking for.  

We don't have other documentation available at this time.

**Comment by keeganwitt** [comment]
The wiki seems to be back now, thank you.
