### ISSUE TITLE
Occasional, but persistent network timeouts

### ISSUE THREAD

**Issue by scovetta** [microsoft/OSSGadget#240]
A few times, OSS Gadget has gotten itself into a situation where the network seems to be timing out, or at least having very long (60+ second) delays. It continues through multiple runs of the tool, including when started from different PowerShell processes. It doesn't occur when run from a Docker container on the same host, nor from Edge.

Visibly, it looks like the HttpConnectionPool / ConnectAsync method is just "waiting"...

After a bunch of trial and error, I came upon: [dotnet/runtime#47267](https://github.com/dotnet/runtime/issues/47267), which contain a workaround that fixes the problem. It seems to disable IPv6 connections, so we don't want to keep this around unnecessarily, but it looks like the fix will only be made in .NET 6.

**Comment by gfs** [comment]
We have switched to .NET 6.
