### ISSUE TITLE
[oss-detect-cryptography] Bad array index on DetectCryptographyTool:549

### ISSUE THREAD

**Issue by scovetta** [microsoft/OSSGadget#279]
When analyzing left-pad during testing, I'm getting:

![image](https://user-images.githubusercontent.com/732166/141655160-21df26ea-9f8e-4ec0-b5a9-2b02d9d488ec.png)

**Comment by gfs** [comment]
I can reproduce but having trouble getting visual studio to let me step to the actual line this is throwing on. We wanted to switch t oapplication inspector anyway so maybe i'll do that next week.

**Comment by gfs** [comment]
I believe this was fixed with #292.
