### ISSUE TITLE
Add linting of some kind to the solution.

### ISSUE THREAD

**Issue by jpinz** [microsoft/OSSGadget#281]
On the Terrapin team we use [Stylecop](https://github.com/StyleCop/StyleCop) to make sure we follow a consistent code styling and documentation styling in our repository.

I've noticed while poking around the OSSGadget repo, that there's a lot of inconsistencies across the code styling and documentation and so on.

I wouldn't say something like this is "Necessary" or even all that important, but someone who is new to the codebase and trying to understand it and work with it, a consistent styling + linting enforcement would be helpful.

Feel free to shoot me a message on teams or an email about it if you want to see the rules we use in our solution.

**Comment by scovetta** [comment]
Good point, I think we used CodeMaid in some other projects -- but yes, we should try to be a bit more consistent. (And I'll apologize in advance, most of the "which of these is not like the other" probably comes from me.) :-)

**Comment by jpinz** [comment]
No worries! Just figured that adding linting is better to do sooner rather than laterr.

**Comment by gfs** [comment]
No objection here to adding linting. If you have a particular recommendation that makes this easy (and works in Visual Studio) I'm all ears. Previously I've just used the built in visual studio styler on demand.

**Comment by gfs** [comment]
I checked out stylecop and it looks like it will probably work fine.  It definitely identifies many issues. I can plan to do a linting PR after the merge of #277, just to not confuse the actual functionality changes with a huge PR that affects every file.

**Comment by gfs** [comment]
#277 adds an .editorconfig and I've run code cleanup on find-squats, domain-squats and tests.  I can plan to do a final linting once we are happy with the PR before merge using the .editorconfig.

**Comment by gfs** [comment]
#277 has had linting done on:

FindSquats
FindSquatsLib
FindDomainSquats
Tests
Shared

The other projects will need a separate PR for linting.
