### ISSUE TITLE
oss-metadata does not support golang

### ISSUE THREAD

**Issue by hectorj2f** [microsoft/OSSGadget#288]
I was trying to run `oss-metadata` for golang packages, and also using the one in the examples: `oss-metadata pkg:golang/sigs.k8s.io/yaml`. However I always get the same error `Error identifying source repository for pkg:golang/sigs.k8s.io/yaml: GolangProjectManager does not implement GetPackageMetadata.`.

 Is there any ETA to add support for golang packages ?

**Comment by gfs** [comment]
There is no current timeline for adding a metadata implementation for the golang manager.

**Comment by gfs** [comment]
I've investigated this more.  It appears that the go API does not actually return much meaningful information for the metadata command.

https://go.dev/ref/mod#goproxy-protocol

In fact, it appears that it will only return the timestamp of the version.  This means we can't really populate any of the metadata.

For example, this is the full amount of info you get when querying the manager for package information: https://proxy.golang.org/golang.org/x/oauth2/@v/v0.0.0-20211104180415-d3ed0bb246c8.info

We could download the whole file but go.mod files don't contain metadata the same way other packages (like a C# CSproj) may.

I don't currently see a path toward automating this until google improves the API of the proxy endpoint to return more data.

**Comment by scovetta** [comment]
With #338 merged, this is now implemented (via either deps.dev or libraries.io)

```
# oss-metadata pkg:golang/sigs.k8s.io/yaml

   ____   _____ _____    _____           _            _
  / __ \ / ____/ ____|  / ____|         | |          | |
 | |  | | (___| (___   | |  __  __ _  __| | __ _  ___| |_
 | |  | |\___ \\___ \  | | |_ |/ _` |/ _` |/ _` |/ _ \ __|
 | |__| |____) |___) | | |__| | (_| | (_| | (_| |  __/ |_
  \____/|_____/_____/   \_____|\__,_|\__,_|\__, |\___|\__|
                                            __/ |
                                           |___/
OSS Gadget - oss-metadata 0.1.357+c946c93324 - github.com/Microsoft/OSSGadget
INFO  - Collecting metadata for pkg:golang/sigs.k8s.io/yaml
{
  "package": {
    "system": "GO",
    "name": "sigs.k8s.io/yaml"
  },
  "owners": [],
  "version": {
    "version": "v1.3.0",
    "symbolicVersions": [],
    "refreshedAt": 1670158508,
    "isDefault": true,
    "licenses": [
      "MIT",
      "BSD-3-Clause"
...
```

This works for the deps.dev and libraries.io data sources, but not for the native one -- tracking via #382.
