### ISSUE TITLE
Please add examples of usage and reports

### ISSUE THREAD

**Issue by sergiomarotco** [microsoft/OSSGadget#317]
I watching https://github.com/microsoft/OSSGadget/wiki/OSS-Defog and I don't really understand what I get as output.
Is it possible to place sample reports in the repository?

**Comment by scovetta** [comment]
Yes, that's a great suggestion. The purpose of the tool is to find obfuscated strings with a package, or folder. Here's a quick example:

```
root@d6adcf35f75b:/usr/src/app# SECRET=$(echo "Hello, my name is Michael." | base64)
root@d6adcf35f75b:/usr/src/app# echo $SECRET
SGVsbG8sIG15IG5hbWUgaXMgTWljaGFlbC4K
root@d6adcf35f75b:/usr/src/app# mkdir tests
root@d6adcf35f75b:/usr/src/app# echo "SECRET=$SECRET" > tests/foo
root@d6adcf35f75b:/usr/src/app# cat tests/foo
SECRET=SGVsbG8sIG15IG5hbWUgaXMgTWljaGFlbC4K
root@d6adcf35f75b:/usr/src/app# oss-defog tests

   ____   _____ _____    _____           _            _
  / __ \ / ____/ ____|  / ____|         | |          | |
 | |  | | (___| (___   | |  __  __ _  __| | __ _  ___| |_
 | |  | |\___ \\___ \  | | |_ |/ _` |/ _` |/ _` |/ _ \ __|
 | |__| |____) |___) | | |__| | (_| | (_| | (_| |  __/ |_
  \____/|_____/_____/   \_____|\__,_|\__,_|\__, |\___|\__|
                                            __/ |
                                           |___/
OSS Gadget - oss-defog 0.1.317+55078cf84c - github.com/Microsoft/OSSGadget
INFO  - [String] tests/foo: SGVsbG8sIG15IG5hbWUgaXMgTWljaGFlbC4K -> Hello, my name is Michael.
```
The output shows that the string `Hello, my name is Michael.` was found in the tests directory.

**Comment by gfs** [comment]
I updated the wiki page with your example Mike.

I can add a few test cases to the repo as well.

**Comment by gfs** [comment]
The wiki has been updated. I checked and the tests demonstrate a number of things it detects already and a few methods of use.  I think this is now covered.

https://github.com/microsoft/OSSGadget/blob/main/src/oss-tests/DefoggerTests.cs
