### ISSUE TITLE
oss-health complains about missing GITHUB_ACCESS_TOKEN even when it's set

### ISSUE THREAD

**Issue by shaunmlowry** [microsoft/OSSGadget#322]
oss-health doesn't seem to be able to read GITHUB_ACCESS_TOKEN from the environment, even when it's set

**Comment by shaunmlowry** [comment]
https://github.com/microsoft/OSSGadget/pull/321

**Comment by gfs** [comment]
Sorry for the regression. 

Thanks for reporting and identifying the fix!

Looks simple enough should have a new version out shortly.

**Comment by gfs** [comment]
Should be merged now.
