### ISSUE TITLE
Wildcard downloads broken for NuGet

### ISSUE THREAD

**Issue by scovetta** [microsoft/OSSGadget#331]
I noticed that NuGet wildcard downloads are broken, see screenshot below.

![image](https://user-images.githubusercontent.com/732166/163694515-c8b77798-b35c-4dc1-b37a-728980f0e08e.png)

This is using version 0.1.332 on Windows.

I'm expecting the wildcard version to mean "download all available versions".

Similar for another NuGet project.
![image](https://user-images.githubusercontent.com/732166/163694535-63ae958a-0708-454a-92bf-bfbf0c269dfd.png)

This works for npm:
![image](https://user-images.githubusercontent.com/732166/163694546-9d3882bc-ba5e-4b6c-b439-4e1c54405842.png)

**Comment by scovetta** [comment]
FYI, this works properly on 0.1.312, it's probably related to the refactoring to use the NuGet library instead of going direct.

![image](https://user-images.githubusercontent.com/732166/163694989-df0ebcdf-b166-455a-825c-f525e1afc8df.png)

**Comment by jpinz** [comment]
I'll look into it now!

**Comment by jpinz** [comment]
@scovetta Hopefully should be fixed now. Let me know if you run into any other issues.
