### ISSUE TITLE
How to use the OSSGadget to detect the local packages

### ISSUE THREAD

**Issue by lxyeternal** [microsoft/OSSGadget#373]
At the moment, OSSGadget only support to detect the online packages from Pypi.org etc. Now I have many malicious packages only in local. I want to know how I can use the OSSGadget tool to detect these.

**Comment by scovetta** [comment]
Hi @lxyeternal! Some of the OSS Gadget tools also accept a directory for local scanning. If memory serves, `oss-detect-backdoor c:\whatever` should work for you.
