### ISSUE TITLE
PackageURL implementation does not recognize packages of the form pkg:npm/@types/react

### ISSUE THREAD

**Issue by jacobmsft** [microsoft/OSSGadget#42]
The parsing logic need to recognize the above name format, which is supposed to be valid:
pkg:npm/@types/react => https://www.npmjs.com/package/@types/react
It gives an error as of now:
: Invalid purl: Does not contain a minimum of a 'type' and a 'name'

**Comment by scovetta** [comment]
You need to escape that second slash -- should work as pkg:npm/%40types%2Freact (if I remember the hex codes correctly).

**Comment by jacobmsft** [comment]
I see, sounds good

**Comment by jacobmsft** [comment]
pkg:npm/%40types/react also works
