### ISSUE TITLE
Please change Reproducible to another term, e.g., Semantically reproducible

### ISSUE THREAD

**Issue by david-a-wheeler** [microsoft/OSSGadget#422]
Please change "reproducible" to another term like "semantically reproducible" or "quasi-reproducible".

The reproducible builds project has always defined "reproducible" as "bit-for-bit" & that's not what you mean. I think it'd be *much* clearer if you used a different term, and then defined the term.

E.g., "Semantically reproducible. A project build is semantically reproducible if its build results can be either recreated exactly (a "reproducible build"), *or* the differences between the release package and a rebuilt package will not impact execution of the package in normal cases. E.g., the rebuilt package might have different date/time stamps, one one might include files like `.gitignore` that are not in the other and would not change the execution of a program under normal circumstances (it's expected that a code review would immediately identify such situations as suspicious).".

**Comment by gfs** [comment]
Thanks for the feedback @david-a-wheeler. I think that's a fair point. To be clear, is this a request to change the name of the `oss-reproducible` tool or moreso to update the Readme for that tool to correctly draw the distinction between exact reproducibility vs semantic reproducibility?

**Comment by david-a-wheeler** [comment]
No need to change the filename. It's the README and any human-readable view I'm focused on.

**Comment by gfs** [comment]
Got it. How does https://github.com/microsoft/OSSGadget/pull/423 look?

**Comment by gfs** [comment]
I think this resolved with #423. If you see anything else amiss don't hesitate to reach back out.

**Comment by david-a-wheeler** [comment]
Thanks! I think it works really well. Thanks for the quick response!
