### ISSUE TITLE
Top-level README doesn't note oss-reproducible nor link to its README

### ISSUE THREAD

**Issue by david-a-wheeler** [microsoft/OSSGadget#424]
It's not obvious from the top-level readme that oss-reproducible exists, nor that it can measure semantic reproducibility.

I *think* it could just be added to the list of tools, with a link to src/README.md, but I'm not certain. In any case, I'd like *something* in the top-level README with a link to the details about semantic reproducibility; I view this capability and potentially important and currently hard to find.

I want to link others to the OSSGadget README to explain semantic reproducibility, but it has to be there first :-).

**Comment by david-a-wheeler** [comment]
I was going to create a PR, but it looks like the README links to the wiki (which is different).

So, I'd like to see the front README link to a wiki page, e.g., the page:
https://github.com/microsoft/OSSGadget/wiki/OSS-Reproducible

In that page I'd like to see contents like this (using [OSS-Defog](https://github.com/microsoft/OSSGadget/wiki/OSS-Defog) as a template and the [oss-reproducible README](https://github.com/microsoft/OSSGadget/blob/main/src/oss-reproducible/README.md)

====

The purpose of OSS reproducible is to analyze open source packages for semantic reproducibility. We start with an existing package (for example, the NPM "left-pad" package, version 1.3.0), and we try to answer the question, How accurately does the source code represent the published package?

Semantically reproducible builds give confidence that packages are derived from the source code that produced them.

A project build is `semantically reproducible` if its build results can be either recreated exactly (a bit for bit [reproducible build](https://en.wikipedia.org/wiki/Reproducible_builds)), or if the differences between the release package and a rebuilt package are not expected to produce functional differences in normal cases.

For example, the rebuilt package might have different date/time stamps, or one might include files like .gitignore that are not in the other and would not change the execution of a program under normal circumstances.

The tool works by applying various strategies to see if it can create a semantically reproducible build.

For more information see the [oss-reproducible README](https://github.com/microsoft/OSSGadget/blob/main/src/oss-reproducible/README.md).

**Comment by gfs** [comment]
@david-a-wheeler thanks for the proposed content for the page. That looks good to me. 

I created the oss reproducible wiki page so it can be linked to from the main readme. 

I'll circle back to add usage examples later. #425
