### ISSUE TITLE
How to inspect source code without metainfo

### ISSUE THREAD

**Issue by Flying-Tom** [microsoft/OSSGadget#449]
I have collected some malicious package (only source code files), but there is no metadata available (the original package may have been delisted from software register). How can I use OSSGadget to inspect these codes?

**Comment by scovetta** [comment]
@Flying-Tom Most of the OSS Gadget tools should also accept a file path to scan, so in the case of OSS Detect Backdoor:



![Image](https://github.com/microsoft/OSSGadget/assets/732166/b299e4f0-c1db-4be5-a4f4-b82bb0d889eb)

**Comment by Flying-Tom** [comment]
Thank you very much!!!! I have another question: Is there an option to include line numbers in the given code context?

**Comment by Flying-Tom** [comment]
According to the code, this functionality might not have been implemented yet？

https://github.com/microsoft/OSSGadget/blob/ca44744983eb85c22c494251d4e43b6905cdcab7/src/oss-detect-backdoor/DetectBackdoorTool.cs#L124-L132

**Comment by scovetta** [comment]
Correct, we don't currently emit line numbers, but the information should be available within the MatchRecord object. If you're interested in sending a pull request, I think it'd be a nice addition to the output!
